routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PertanyaanController@index');

Route::get('/welcoming', function () {
    return view('welcoming');
});

Route::get('/register', function () {
    return view('register');
});

Route::post('/form_post', 'AuthController@form_post');

Route::get('/master', function(){
    return view('adminlte.master');
});

Route::get('/items',function(){
    return view('items.index');
});

Route::get('/data-tables',function(){
    return view('adminlte.partials.data-tables');
});

// Route::get('/pertanyaan','PertanyaanController@index');
// Route::get('/pertanyaan/create','PertanyaanController@create');
// Route::post('/pertanyaan','PertanyaanController@store');
// Route::get('/pertanyaan/{id}','PertanyaanController@show');
// Route::get('/pertanyaan/{id}/edit','PertanyaanController@edit');
// Route::put('/pertanyaan/{id}','PertanyaanController@update');
// Route::delete('/pertanyaan/{id}','PertanyaanController@destroy');

Route::resource('pertanyaan','PertanyaanController');
Route::get('/pertanyaan/{pertanyaan}/like','PertanyaanController@like')->name('pertanyaan.like');
Route::get('/pertanyaan/{pertanyaan}/dislike','PertanyaanController@dislike')->name('pertanyaan.dislike');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/test-dompdf', function(){
    $pdf = App::make('dompdf.wrapper');
    $pdf->loadHTML('<h1>Test</h1>');
    return $pdf->stream();
});

Route::get('export/', 'PertanyaanController@export');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::get('/demo-filemgr',function(){
    return view('file-manager.demo');
});

Route::post('/logout',"HomeController@logout");

Route::get('/jawaban/create/{jawaban}',['as' => "jawaban.create", 'uses' => "JawabanController@create"]);
Route::resource('jawaban','JawabanController', ['names' => [
    'create' => 'jawaban.create2'
    ]]);

Route::get('/jawaban/{jawaban}/like','JawabanController@like')->name('jawaban.like');
Route::get('/jawaban/{jawaban}/dislike','JawabanController@dislike')->name('jawaban.dislike');

Route::get('/jawaban/komentarjawaban/{pertanyaan}/{jawaban}',['as' => "komentar_jawaban.create", 'uses' => "komentarJawabanController@create"]);
Route::post('/jawaban/komentarjawaban','komentarJawabanController@store');
Route::delete('/jawaban/komentarjawaban/{komentarJawaban}','komentarJawabanController@destroy')->name('komentar_jawaban.destroy');

Route::get('/komentarjawaban/{komentar_jawaban}/like','komentarJawabanController@like')->name('komentar_jawaban.like');
Route::get('/komentarjawaban/{komentar_jawaban}/dislike','komentarJawabanController@dislike')->name('komentar_jawaban.dislike');

Route::get('komentarpertanyaan/{pertanyaan}/create','KomentarPertanyaanController@create') -> name('komentarpertanyaan.create');
Route::resource('komentarpertanyaan','KomentarPertanyaanController', ['names' => [
    'create' => 'komentar_pertanyaan.create2'
    ]]);


Route::get('/about',function(){
    return view('about.about');
});

Route::get('/komentarpertanyaan/{komentarpertanyaan}/like','KomentarPertanyaanController@like')->name('komentarpertanyaan.like');
Route::get('/komentarpertanyaan/{komentarpertanyaan}/dislike','KomentarPertanyaanController@dislike')->name('komentarpertanyaan.dislike');

app/Pertanyaan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cog\Contracts\Love\Reactable\Models\Reactable as ReactableInterface;
use Cog\Laravel\Love\Reactable\Models\Traits\Reactable;

class Pertanyaan extends Model implements ReactableInterface
{
    use Reactable;
    protected $table = 'pertanyaan';
    protected $guarded = [];

    public function user(){
        return $this->belongsTo('App\User','profil_id');
    }

    public function jawabanTepat(){
        return $this->hasOne('App\Jawaban','jawaban_tepat_id');
    }

    public function tag(){
        return $this->belongsToMany('App\Tag');
    }

    public function jawaban(){
        return $this->hasMany('App\Jawaban');
    }

    public function komentar_pertanyaan(){
        return $this->hasMany('App\komentarPertanyaan','pertanyaan_id');
    }
}

app/Http/Controllers/PertanyaanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Pertanyaan;
use App\Jawaban;
use App\Profil;
use App\komentarJawaban;
Use Auth;
use App\Tag;
use App\Exports\PertanyaanExport;
use Maatwebsite\Excel\Facades\Excel;
use Alert;
Use ReactionType;

class PertanyaanController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth') -> except(['index']) ;
    }

    public function index(){
        $data_pertanyaan = Pertanyaan::all();
        // $reactantFacade = $data_pertanyaan->viaLoveReactant();
        return view('pertanyaan.index', compact('data_pertanyaan'));
    }

    public function create(){
        return view('pertanyaan.create');
    }

    public function store(Request $request){
        date_default_timezone_set('Asia/Jakarta');
        $request->validate([
            'judul_pertanyaan' => 'required|max:255',
            'isi_pertanyaan' => 'required'
        ]);

        $tags_arr = explode(',',$request['tag']);

        $tag_ids = [];
        foreach($tags_arr as $tag_name){
            $tag = Tag::firstOrCreate(['tag' => $tag_name]);
            $tag_ids[] = $tag->id;
        }

        $user = Auth::user();

        $pertanyaan = $user->pertanyaan() -> create([
            'judul' => $request['judul_pertanyaan'],
            'isi' => $request['isi_pertanyaan'],
            'tanggal_dibuat' => date('y/m/d')

        ]);

        $pertanyaan->tag()->sync($tag_ids);


        Alert::success('Berhasil', 'Pertanyaan berhasil disimpan!');

        return redirect('/pertanyaan')->with('success', 'Pertanyaan berhasil disimpan!');
    }

    public function update($id, Request $request){
        date_default_timezone_set('Asia/Jakarta');
        $request->validate([
            'judul_pertanyaan' => 'required|max:255',
            'isi_pertanyaan' => 'required'
        ]);

        $pertanyaan = Pertanyaan::find($id) -> update ([
            'judul' => $request['judul_pertanyaan'],
            'isi' => $request['isi_pertanyaan'],
            'tanggal_diperbarui' => date('y/m/d'),
        ]);
        return redirect('/pertanyaan')->with('success', 'Data pertanyaan berhasil diubah!')  ;
    }

    public function show($id){
        $pertanyaan = Pertanyaan::find($id);
        $data_jawaban = Jawaban::where('pertanyaan_id',$id)->get();
        $data_komentar_jawaban = komentarJawaban::with('jawaban')->get();
        $reactantFacade = $pertanyaan->viaLoveReactant();
        $data_komentar_jawaban = komentarJawaban::all();
        // $reaction_like_counter = $reactantFacade->getReactionCounterOfType('Like');
        return view('pertanyaan.show',compact('pertanyaan','data_jawaban','reactantFacade','data_komentar_jawaban'));
    }

    public function edit($id){
        $pertanyaan = Pertanyaan::with('user')->find($id);
        $tags_arr = [];
        foreach($pertanyaan -> tag as $tag){
            $tags_arr[] = $tag->tag;
        }
        return view('pertanyaan.edit',compact('pertanyaan','tags_arr'));
    }

    public function destroy($id){
        Pertanyaan::destroy($id);
        return redirect('/pertanyaan')->with('success', 'Data berhasil dihapus!')  ;
    }

    public function export()
    {
        return Excel::download(new PertanyaanExport, 'pertanyaan.xlsx');
    }

    public function like($id)
    {
        $user = Auth::user();
        $reacterFacade = $user->viaLoveReacter();

        $pertanyaan = Pertanyaan::find($id);
        $reacterFacade->reactTo($pertanyaan, 'Like');

        return redirect()->route('pertanyaan.show',["pertanyaan"=>$pertanyaan]);
    }

    public function dislike($id)
    {
        $user = Auth::user();
        $reacterFacade = $user->viaLoveReacter();

        $pertanyaan = Pertanyaan::find($id);
        $reacterFacade->reactTo($pertanyaan, 'Dislike');

        return redirect()->route('pertanyaan.show',["pertanyaan"=>$pertanyaan]);
    }

}

resources/views/pertanyaan/create.blade.php
@extends('adminlte.master')

@push('script-head')
    <script src="https://cdn.tiny.cloud/1/c708l487stbibqc62750iszmeyhq1oxoqcmparc625aejcod/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
@endpush

@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Buat Pertanyaan Baru</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/pertanyaan">Home</a></li>
                    <li class="breadcrumb-item active">General Form</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<form role="form" method="POST" action="/pertanyaan">
    @csrf
    <div class="card-body">
        <!--
        <div class="form-group">
            <label for="inputProfilId">Profil ID</label>
            <input type="text" class="form-control" name= "profil_id" id="inputProfilId" placeholder="Profil ID" value="{{ Auth::id() }}" disabled>
        </div>
        -->
        <div class="form-group">
            <label for="userName">Nama Lengkap</label>
            <input type="text" class="form-control" name= "userName" id="userName" placeholder="Nama Lengkap" value="{{ Auth::user() -> name }}" disabled>
        </div>
        <div class="form-group">
            <label for="judulPertanyaan">Judul</label>
            <input type="text" class="form-control" name="judul_pertanyaan" id="judulPertanyaan" placeholder="Judul pertanyaan" value="{{old('judul_pertanyaan','')}}">
            @error('judul_pertanyaan')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="tag">Tags</label>
            <input data-role = "tagsinput" type='text' class="form-control" name="tag" id="tag" placeholder="Tags..." value="{{old('tag','')}}">
            @error('tag')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="isi_pertanyaan">Pertanyaan</label>
            <textarea id="isi_pertanyaan" name="isi_pertanyaan" class="my-editor form-control" rows="15">{!! old('isi_pertanyaan', '') !!}</textarea>
            @error('isi_pertanyaan')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
    </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>

@endsection

@push('script')
<script>
  var editor_config = {
    path_absolute : "/",
    selector: "textarea.my-editor",
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
    relative_urls: false,
    file_browser_callback : function(field_name, url, type, win) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
      if (type == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.open({
        file : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no"
      });
    }
  };

  tinymce.init(editor_config);
</script>

@endpush

resources/views/pertanyaan/edit.blade.php
@extends('adminlte.master')
@push('script-head')
<script src="https://cdn.tiny.cloud/1/c708l487stbibqc62750iszmeyhq1oxoqcmparc625aejcod/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
@endpush

@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Edit Pertanyaan {{ $pertanyaan->id }} </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item active">General Form</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<form role="form" method="POST" action="/pertanyaan/{{ $pertanyaan->id }} ">
    @csrf
    @method('PUT')
    <div class="card-body">
        <div class="form-group">
            <label for="profilId">Profil ID</label>
            <input type="text" class="form-control" name= "profil_id" id="profilId" value="{{ $pertanyaan -> profil_id }}" disabled>
        </div>
        <div class="form-group">
            <label for="namaLengkap">Nama Lengkap</label>
            <input type="text" class="form-control" name= "namaLengkap" id="namaLengkap" value="{{ $pertanyaan -> user['name'] }}" disabled>
        </div>
        <div class="form-group">
            <label for="judulPertanyaan">Judul</label>
            <input type="text" class="form-control" name="judul_pertanyaan" id="judulPertanyaan" placeholder="Judul pertanyaan" value="{{old('judul_pertanyaan',$pertanyaan -> judul)}}">
            @error('judul_pertanyaan')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="tag">Tags</label>
            <input data-role = "tagsinput" type='text' class="form-control" name="tag" id="tag" placeholder="Tags..." value="{{ implode(',',$tags_arr) }}">
            @error('tag')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="isiPertanyaan">Pertanyaan</label>
            <textarea class="my-editor form-control" name="isi_pertanyaan" id="isiPertanyaan" rows = "10" placeholder="Pertanyaan anda...">{{old('isi_pertanyaan',$pertanyaan -> isi)}}</textarea>
            @error('isi_pertanyaan')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
    </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>

@endsection

@push('script')
    <script>
    var editor_config = {
        path_absolute : "/",
        selector: "textarea.my-editor",
        plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor colorpicker textpattern"
        ],
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
        relative_urls: false,
        file_browser_callback : function(field_name, url, type, win) {
        var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
        var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

        var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
        if (type == 'image') {
            cmsURL = cmsURL + "&type=Images";
        } else {
            cmsURL = cmsURL + "&type=Files";
        }

        tinyMCE.activeEditor.windowManager.open({
            file : cmsURL,
            title : 'Filemanager',
            width : x * 0.8,
            height : y * 0.8,
            resizable : "yes",
            close_previous : "no"
        });
        }
    };

    tinymce.init(editor_config);
    </script>
@endpush

resources/views/pertanyaan/index.blade.php
@extends('adminlte.master')

@section('content')
    <div class="card">
        <div class="card-header">
            <h1 class="card-title">Data Pertanyaan</h1>
            <div class="card-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
            @if(session('success'))
                <div class="alert alert-success ml-2" role="alert">
                    {{ session('success') }}
                </div>
            @endif
            <a class="btn btn-primary mb-2 ml-2 mt-2" href=" {{route('pertanyaan.create')}} ">Buat pertanyaan baru</a>
            <table class="table table-head-fixed">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama</th>
                        <th>Judul</th>
                        <th>Pertanyaan</th>
                        <th>Tanggal Dibuat</th>
                        <th>Tanggal Diperbarui</th>
                        <th>Likes</th>
                        <th>Dislikes</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data_pertanyaan as $key => $value)
                    <tr>
                        <td> </td>
                        <td> {{ $value -> user['name'] }} </td>
                        <td> {{ $value -> judul }} </td>
                        <td> {!! $value -> isi !!} </td>
                        <td> {{ $value -> tanggal_dibuat }} </td>
                        <td> {{ $value -> tanggal_diperbarui }} </td>
                        <td> {{ $value -> viaLoveReactant()->getReactionCounterOfType('Like')->getCount() }} </td>
                        <td> {{ $value -> viaLoveReactant()->getReactionCounterOfType('Dislike')->getCount() }} </td>
                        <td style="display:flex">
                            <a href=" {{route('pertanyaan.show', ['pertanyaan' => $value->id] )}} "  role="button" class="btn btn-primary btn-sm">show</a>
                            @if(Auth::check() && (Auth::user()->id == $value->user['id']))
                            <a href=" {{route('pertanyaan.edit', ['pertanyaan' => $value->id] )}} "  role="button" class="btn btn-dark btn-sm ml-1 private">edit</a>
                            <form action=" {{route('pertanyaan.destroy', ['pertanyaan' => $value->id] )}} " method="POST">
                                @csrf
                                @method('DELETE')
                                <input type="submit" value="delete" class="btn btn-danger btn-sm ml-1">
                            </form>
                            @endif
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>


@endsection